[cli] Migrate `logout` command to new structure
vercel/vercel pull request #10282
Opened 2023-07-31 14:41 UTC by trek

Before:
<img width="551" alt="CleanShot 2023-07-31 at 09 40 48@2x" src="https://github.com/vercel/vercel/assets/9736/408d550c-251e-43cf-976d-83d837d446bd">

After:
<img width="679" alt="CleanShot 2023-07-31 at 09 41 04@2x" src="https://github.com/vercel/vercel/assets/9736/978be3de-97a0-4657-a83d-ad6c7f0110fa">

2023-07-31 22:39 UTC, cb1kenobi requested changes
There seems to be a bit of excess whitespace when the command has no options: 
<img width="389" alt="image" src="https://github.com/vercel/vercel/assets/97262/007f954d-b7bc-4cab-9fe0-e8c85ad969b9">

2023-08-01 13:35 UTC, trek commented
@cb1kenobi can we put that into the work for fixing spacing?

2023-08-01 15:37 UTC, cb1kenobi commented on packages/cli/src/commands/logout/command.ts
> +  description: 'Logout of the currently authenticated user or team.',
Something about this reads funny. How do you feel about slimming it down?

```suggestion
  description: 'Logout the current authenticated user or team.',
```

2023-08-02 13:56 UTC, cb1kenobi approved these changes

2023-08-02 13:59 UTC, merged