Handle calls for deployment aliases when mocking deployment API
vercel/vercel pull request #10303
Opened 2023-08-04 15:36 UTC by trek

2023-08-04 20:37 UTC, dan-stowell submitted a review, later dismissed

2023-08-07 13:32 UTC, cb1kenobi requested changes

2023-08-07 13:32 UTC, cb1kenobi commented on packages/cli/test/mocks/deployment.ts
> +  client.scenario.get('/now/deployments/:id/aliases', (req, res) => {
We should probably treat the first path segment as a version as described in the docs: https://vercel.com/docs/rest-api/endpoints#list-deployment-aliases

```suggestion
  client.scenario.get('/:version/deployments/:id/aliases', (req, res) => {
```

2023-08-07 13:32 UTC, cb1kenobi commented on packages/cli/test/mocks/deployment.ts
> +      aliases: deployment?.alias ? [deployment.alias] : [],
I believe `deployment.alias` is a string. The `aliases` return value is an array of objects:

```
{
  uid: string;
  alias: string;
  created: string;
  redirect?: string | null;
  protectionBypass?: {
    [key: string]:
      | { createdAt: number; createdBy: string; scope: 'sharable-link' | 'automation-bypass'; }
      | { createdAt: number; lastUpdatedAt: number; lastUpdatedBy: string; access: 'requested' | 'granted'; scope: 'user'; }
  }
}[]
```

2023-08-07 14:19 UTC, cb1kenobi approved these changes

2023-08-07 14:34 UTC, merged