[cli] [WIP] Use "esbuild"
vercel/vercel pull request #10555
Opened 2023-09-20 21:42 UTC by TooTallNate

2023-09-21 14:59 UTC, EndangeredMassa requested changes
Tested manually and everything seemed to work fine!

2023-09-21 14:59 UTC, EndangeredMassa commented on packages/cli/scripts/compile-templates.js
> +  //);
<!-- Suggestion comments propose improvements to the code. Mention specifically what should be changed and what the benefit would be.  -->
**suggestion (blocking):** ‏I'm no fan of prettier, but we should probably restore this

2023-09-21 14:59 UTC, EndangeredMassa commented on packages/cli/src/index.ts
> +// cache bust
<!-- Suggestion comments propose improvements to the code. Mention specifically what should be changed and what the benefit would be.  -->
**suggestion (blocking):** ‏remove

```suggestion
```

2023-09-21 14:59 UTC, EndangeredMassa commented on packages/cli/build.mjs
> +//await remove(join(dirRoot, '../../node_modules/fsevents'));
<!-- Questions comments seek clarification.  -->
**question (blocking):** ‏do we need this?

2023-09-21 14:59 UTC, EndangeredMassa commented on packages/cli/build.mjs
> +//});
<!-- Questions comments seek clarification.  -->
**question (blocking):** ‏do we need this?

2023-09-21 15:12 UTC, TooTallNate commented on packages/cli/build.mjs
> +//await remove(join(dirRoot, '../../node_modules/fsevents'));
No because `chokidar` dep was moved to "dependencies" (fsevents is a dep of chokidar).

2023-09-21 15:12 UTC, TooTallNate commented on packages/cli/build.mjs
> +//});
No because `@vercel/fun` dep was moved to "dependencies". I'll push some cleanup changes to this build script though.

2023-09-21 15:55 UTC, TooTallNate commented on packages/cli/scripts/compile-templates.js
> +  //);
I'd prefer not actually. It was always kind of strange to me to run prettier on an already generated file that we never manually look at, but my OCD at the time didn't care about compile time. Here's a comparison, lmk if you still feel strongly:

### Before

```ts
import encodeHTML from 'escape-html';

interface Inputs {
  app_error: boolean;
  title: string;
  subtitle?: string;
  http_status_code: number;
  http_status_description: string;
  error_code?: string;
  request_id: string;
}

export default function error_404(it
) {
let encodeHTML = typeof _encodeHTML !== 'undefined' ? _encodeHTML : (function(doNotSkipEncoded) {
		let encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());let out='<main> <p class="devinfo-container"> <span class="error-code"><strong>'+( it.http_status_code )+'</strong>: '+encodeHTML( it.http_status_description )+'</span> ';if(it.error_code){out+=' <span class="devinfo-line">Code: <code>'+encodeHTML( it.error_code )+'</code></span> ';}out+=' <span class="devinfo-line">ID: <code>'+encodeHTML( it.request_id )+'</code> </p></main>';return out;
}
```

### After

```ts
import encodeHTML from 'escape-html';

interface Inputs {
  app_error: boolean;
  title: string;
  subtitle?: string;
  http_status_code: number;
  http_status_description: string;
  error_code?: string;
  request_id: string;
}

export default function error_404(it) {
  let encodeHTML =
    typeof _encodeHTML !== 'undefined'
      ? _encodeHTML
      : (function (doNotSkipEncoded) {
          let encodeHTMLRules = {
              '&': '&#38;',
              '<': '&#60;',
              '>': '&#62;',
              '"': '&#34;',
              "'": '&#39;',
              '/': '&#47;',
            },
            matchHTML = doNotSkipEncoded
              ? /[&<>"'\/]/g
              : /&(?!#?\w+;)|<|>|"|'|\//g;
          return function (code) {
            return code
              ? code.toString().replace(matchHTML, function (m) {
                  return encodeHTMLRules[m] || m;
                })
              : '';
          };
        })();
  let out =
    '<main> <p class="devinfo-container"> <span class="error-code"><strong>' +
    it.http_status_code +
    '</strong>: ' +
    encodeHTML(it.http_status_description) +
    '</span> ';
  if (it.error_code) {
    out +=
      ' <span class="devinfo-line">Code: <code>' +
      encodeHTML(it.error_code) +
      '</code></span> ';
  }
  out +=
    ' <span class="devinfo-line">ID: <code>' +
    encodeHTML(it.request_id) +
    '</code> </p></main>';
  return out;
}
```

2023-09-21 18:52 UTC, EndangeredMassa commented on packages/cli/scripts/compile-templates.js
> +  //);
Be gone, prettier!

2023-09-21 18:53 UTC, EndangeredMassa approved these changes, later dismissed

2023-09-22 12:25 UTC, merged

2023-09-25 14:45 UTC, martin-dimi commented
Not sure if related, but since Vercel CLI `32.2.5`, we've been getting runtime errors:
```
Error: Cannot find module '/var/task/node_modules/playwright-core/index.mjs' imported from /var/task/bowser/api/_common.js
Did you mean to import playwright-core/index.js?
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: 4405f3c7-cfac-41bb-a30b-8d36bd115b9d Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
Nothing has changed on our side, all dependency versions are also locked so no updates there either.
We've tried building a deployment from a week ago (that we know 100% used to work) and it still gives us the above runtime error.

I suspect it's a bug with Vercel CLI 32.3.1 and maybe this PR. cc @TooTallNate

2023-09-25 15:05 UTC, TooTallNate commented
@martin-dimi Let's keep it contained to [the existing Discussion thread](https://github.com/orgs/vercel/discussions/4231).

2023-10-02 12:54 UTC, empirefam11 commented
npm i -g https://vercel-git-tootallnate-zero-926-use-esbuild-for-vercel-cli.vercel.sh/tarballs/vercel.tgz