[static-build] dojo-v2
vercel/vercel pull request #10689
Opened 2023-10-11 17:41 UTC by Ethan-Arrowood

2023-10-11 18:16 UTC, EndangeredMassa requested changes

2023-10-11 18:16 UTC, EndangeredMassa commented on packages/static-build/test/fixtures/dojo-v2/package.json
> +{
<!-- Requirement comments refer to a task requirements that is not being met by the current code. Mention what the requirement is and why the code does not meet it.  -->
**requirement (blocking):** please ‏add a lockfile

2023-10-11 18:38 UTC, EndangeredMassa approved these changes

2023-10-11 18:42 UTC, cb1kenobi approved these changes

2023-10-12 18:20 UTC, Ethan-Arrowood commented
Dojo isn't playing nicely. Going to backlog this PR and revisit later.

2024-06-21 14:42 UTC, closed without merging