bump: edge-runtime
vercel/vercel pull request #10712
Opened 2023-10-15 09:18 UTC by Kikobeats

It bumps Edge Runtime to include the latest fixes, such as:

- https://github.com/vercel/edge-runtime/pull/622
- https://github.com/vercel/edge-runtime/pull/640

2023-10-16 12:08 UTC, javivelasco approved these changes, later dismissed
Some tests seem to be failing though

2023-10-16 13:56 UTC, cb1kenobi approved these changes

2023-10-16 15:31 UTC, cb1kenobi requested changes, later dismissed
@Kikobeats I see the type check is failing after this change. Can you please take a peek: https://github.com/vercel/vercel/actions/runs/6523217767/job/17743603225?pr=10712#step:9:60.

2023-10-16 15:35 UTC, Ethan-Arrowood submitted a review, later dismissed

2023-11-03 14:59 UTC, cb1kenobi approved these changes
LGTM

2023-11-06 08:58 UTC, merged