Fix changeset lint for forks
vercel/vercel pull request #10737
Opened 2023-10-19 19:42 UTC by csabapalfi

2023-10-19 22:11 UTC, Ethan-Arrowood approved these changes

2023-10-19 22:21 UTC, styfle approved these changes

2023-10-19 22:22 UTC, styfle requested changes
This looks like a bug since `Enforce Changeset` is passing on this PR even though there is no changeset.

2023-10-19 23:19 UTC, csabapalfi commented
@styfle that's because this PR is not changing any of the packages, it only touches `.github/workflows`

2023-10-19 23:29 UTC, styfle approved these changes
You're right!

I confirmed with another PR that it was passing without a changeset.

That's a different bug we need to fix 😅

2023-10-20 17:43 UTC, TooTallNate commented on .github/workflows/test-lint.yml
> +      - run: git checkout pr-${{ github.event.pull_request.number }}
I think this won't work when running on `main`?

2023-10-20 17:43 UTC, TooTallNate requested changes
I think this won't work when running on `main`? What exactly is this fixing btw? There is no description so it's not clear to me.

2023-10-20 21:10 UTC, csabapalfi commented
@TooTallNate apologies for the hastily created PR. Added a description and also checked that `main` won't be affected.

2023-11-28 00:36 UTC, TooTallNate commented
> This will not affect `main` since this check is only run for PRs:
> ```
> if: github.event_name == 'pull_request' && github.event.pull_request.title != 'Version Packages'
> ```

That's only for the Enforce Changeset though. The main Lint job still runs on `main`.

2023-11-28 00:37 UTC, TooTallNate approved these changes

2023-11-28 00:38 UTC, merged

2023-11-28 00:38 UTC, TooTallNate commented
Thanks @csabapalfi, and sorry for the delay.