[cli][tests] Fix `getUpdateCommand` for local dev
vercel/vercel pull request #11276
Opened 2024-03-14 19:53 UTC by onsclom

This unit test fails on my machine:
```
Expected: "pnpm i vercel@latest"
Received: "pnpm i -g vercel@latest"
```

This change allows the test to succeed on machines that need the `-g` flag.

2024-03-14 19:54 UTC, trek approved these changes, later dismissed

2024-03-14 20:28 UTC, TooTallNate requested changes

2024-03-14 20:28 UTC, TooTallNate commented on .changeset/lazy-oranges-sip.md
> +---
Let's delete this one, since it's just a change for the tests. No need for a changelog entry (not user facing).

2024-03-15 23:56 UTC, TooTallNate approved these changes

2024-03-16 00:31 UTC, merged