Include node version range in node engine warning message
vercel/vercel pull request #11742
Opened 2024-06-17 22:18 UTC by jeffsee55

Before this change the warning doesn't show what the resolved version of node actually is. Which is slightly confusing when you have an engine rule like `>=18` and the resolved version is `20x`.

```
Warning: Due to "engines": { "node": ">=18" } in your `package.json` file, the Node.js Version defined in your Project Settings ("18.x") will not apply, Node.js Version "20.x" will be used instead. Learn More: http://vercel.link/node-version
```

2024-06-17 23:14 UTC, TooTallNate commented on packages/build-utils/src/fs/run-user-scripts.ts
> +  console.log({ supportedNodeVersion });
Remove?

```suggestion
```

2024-06-18 23:38 UTC, TooTallNate commented on packages/remix/defaults/server-node.mjs
> +// installGlobals();
Remove?

2024-06-18 23:39 UTC, TooTallNate requested changes, later dismissed

2024-06-18 23:39 UTC, TooTallNate commented on packages/remix/defaults/server-node.mjs
> +// installGlobals();
Revert?

```suggestion
installGlobals();
```

2024-06-20 18:53 UTC, jeffsee55 commented on packages/remix/defaults/server-node.mjs
> +// installGlobals();
Sorry!

2024-06-26 16:36 UTC, erikareads approved these changes

2024-06-28 17:49 UTC, merged