[fs-detectors] Adds new detector for Sanity v3
vercel/vercel pull request #11991
Opened 2024-08-21 21:05 UTC by trek

Sanity v3 has a different `dev` command than Sanity `<3`. This PR adds a new `frameworks` entry for it. Also adds tests to ensure v2 and v3 are detected correctly between each other.

2024-08-21 21:30 UTC, EndangeredMassa submitted a review, later dismissed

2024-08-21 21:30 UTC, EndangeredMassa commented on packages/frameworks/src/frameworks.ts
> +            /"(dev)?(d|D)ependencies":\s*{[^}]*"sanity":\s*"\^?3\..*"[^}]*}/,
<!-- Suggestion comments propose improvements to the code. Mention specifically what should be changed and what the benefit would be.  -->
**suggestion (non-blocking):** ‏We should probably change `matchPackage` to handle versions as well.

2024-08-22 01:28 UTC, TooTallNate commented on packages/frameworks/src/frameworks.ts
> +    name: 'Sanity',
We'll want to use a different name, otherwise this will show up twice in the UI with no way to differentiate between the two.

2024-08-22 01:28 UTC, TooTallNate requested changes

2024-08-22 01:28 UTC, TooTallNate commented on packages/frameworks/src/frameworks.ts
> +    name: 'Sanity',
We'll want to use a different name, otherwise this will show up twice in the UI with no way to differentiate between the two.

2024-08-22 18:10 UTC, trek commented on packages/frameworks/src/frameworks.ts
> -    dependency: '@sanity/cli',
`@sanity/cli` isn't a dependency for Sanity 3+ any longer. Unsure if this comment still applies?

https://github.com/vercel/vercel/blob/9d4d4b6deb6294506016106f78e71f1984adcc7f/packages/frameworks/src/frameworks.ts#L12-L16

Several framework entries don't have this value or don't reference a cli

2024-08-23 13:19 UTC, trek commented on packages/frameworks/src/frameworks.ts
> -    dependency: '@sanity/cli',
cc @TooTallNate @EndangeredMassa

2024-08-23 15:08 UTC, EndangeredMassa commented on packages/frameworks/src/frameworks.ts
> -    dependency: '@sanity/cli',
This is general guidance that on average is still true. I think it's fine.

2024-08-23 15:08 UTC, EndangeredMassa approved these changes

2024-08-23 19:35 UTC, TooTallNate approved these changes

2024-08-26 13:51 UTC, merged