refactor(login): `vercel login` via OAuth Device Authorization flow
vercel/vercel pull request #12098
Opened 2024-09-11 12:31 UTC by balazsorban44

This PR overhauls the `vercel login` experience by building on proper standards, namely the [OAuth Device Authorization](https://datatracker.ietf.org/doc/html/rfc8628) flow.

Closes #11989
Closes #6899, since we are moving away from maintaining CLI login flows.

Fow not, it is behind the `--oauth` flag, so we can keep iterating on it.

**NOTE:** This should not yet be used.

2024-09-17 16:20 UTC, jeffsee55 reviewed
@balazsorban44 is this ready for review? Tried running this locally and got:

```
> pnpm dev login --future
Vercel CLI 37.4.1
WARN! This command is not ready yet. Do not use!
Error: Device authorization request failed
 ELIFECYCLE  Command failed with exit code 1.
```
And there aren't any tests to peek at for hints on how to use, let me know any tips on testing this 🙏

2025-02-21 12:14 UTC, marcgreenstock commented on packages/cli/src/commands/login/future/index.ts
> +  o.warn('This feature is under active development. Do not use!');
Do we need this? Can we not allow for users to begin using it right away?

2025-02-21 12:17 UTC, marcgreenstock commented on packages/cli/src/util/oauth.ts
> +  jwks_uri: new URL('https://vercel.com/api/login/oauth/jwks'),
```suggestion
  jwks_uri: new URL('https://vercel.com/.well-known/jwks'),
```

2025-02-21 13:16 UTC, balazsorban44 commented on packages/cli/src/commands/login/future/index.ts
> +  o.warn('This feature is under active development. Do not use!');
Will drop. :+1:

2025-02-21 13:16 UTC, balazsorban44 commented on packages/cli/src/util/oauth.ts
> +  jwks_uri: new URL('https://vercel.com/api/login/oauth/jwks'),
Probably safer to use the discovery endpoint and not hard-code too much in CLI. Will update!

2025-02-21 13:23 UTC, marcgreenstock approved these changes, later dismissed

2025-02-21 14:33 UTC, trek commented on .changeset/heavy-terms-reply.md
> +"vercel": patch
This is probably technically a minor (introduces new features), but not blocking.

2025-02-21 14:46 UTC, trek requested changes
Looks good to me, other than some comments.

If we don't intend for this to be used, we should *not* merge and release this. Customers will see it and will begin to use it.

If you wanted to get this into the CLI to test, we can help show you some options to before we merge and release!

2025-02-21 14:46 UTC, trek commented on packages/cli/vitest.config.mts
> +    coverage: { reporter: ['html'] },
This is nice to add but seems unrelated to adding login?

2025-02-21 14:46 UTC, trek commented on packages/cli/src/commands/login/index.ts
> +  if (client.argv.slice(2).includes('--future')) return await future(client);
If this is shifted down, `--future` will be available as `parsedArgs.flags['--future']`

2025-02-21 14:46 UTC, trek commented on packages/cli/src/commands/logout/index.ts
> +  if (client.argv.slice(2).includes('--future')) return await future(client);
If this is shifted down, `--future` will be available as `parsedArgs.flags['--future']`

2025-02-21 14:46 UTC, trek commented on packages/cli/test/unit/commands/logout/future.test.ts
> +vi.mock('node-fetch', async () => ({
We have a mock HTTP vercel server stored on the `client` (view a few other unit tests to get a sense for it) that would be preferable to use to avoid introducing a second alternate pattern to the tests.

2025-02-24 09:30 UTC, balazsorban44 commented on packages/cli/test/unit/commands/logout/future.test.ts
> +vi.mock('node-fetch', async () => ({
I first tried using `client`, but decided to use raw `fetch` instead because https://github.com/vercel/vercel/blob/main/packages/cli/src/util/client.ts/#L135-L221 had too much magic (adding/overriding headers, search params) and broke the requests/responses constantly.

We want to strictly follow the OAuth spec, so either I need to modify `client.fetch` via adding a `raw: true` flag to disable unexpected modifications, and refactor the `oauth.ts` file to rely on the `client.fetch`, or we keep the current mocks. Let me know what would be more preferable!

2025-02-24 14:43 UTC, trek approved these changes, later dismissed

2025-02-27 15:36 UTC, trek approved these changes

2025-02-27 23:06 UTC, merged