Upgrade @vercel/nft to 0.27.4
vercel/vercel pull request #12109
Opened 2024-09-12 16:30 UTC by onsclom

Release details: https://github.com/vercel/nft/releases/tag/0.27.4

2024-09-12 16:37 UTC, TooTallNate approved these changes, later dismissed

2024-09-12 20:00 UTC, trek submitted a review, later dismissed

2024-12-19 18:49 UTC, TooTallNate requested changes

2024-12-19 18:49 UTC, TooTallNate commented on .changeset/fresh-steaks-serve.md
> +'vercel': patch
```suggestion
'@vercel/redwood': patch
'@vercel/remix-builder': patch
'@vercel/next': patch
'@vercel/node': patch
```

2024-12-19 18:53 UTC, trek approved these changes, later dismissed

2024-12-19 18:54 UTC, TooTallNate submitted a review, later dismissed

2025-01-02 21:13 UTC, TooTallNate approved these changes

2025-01-03 04:06 UTC, merged