Use `vitest` in client package
vercel/vercel pull request #12530
Opened 2024-11-06 23:22 UTC by jeffsee55

2024-11-07 17:52 UTC, jeffsee55 commented on packages/client/package.json
> -    "test-e2e": "pnpm test tests/create-deployment.test.ts tests/create-legacy-deployment.test.ts tests/paths.test.ts",
`create-legacy-deployment.test.ts` no longer exists

2024-11-13 14:47 UTC, EndangeredMassa submitted a review, later dismissed

2024-11-13 14:47 UTC, EndangeredMassa commented on packages/client/tests/unit.vercelignore.test.ts
> +      }
<!-- Suggestion comments propose improvements to the code. Mention specifically what should be changed and what the benefit would be.  -->
**suggestion (non-blocking):** ‏check else case

If for some reason `_err` is not an `Error`, we should make sure the error shows what it was. Right now, if this test fails for this reason, the failure we'll get is that `err` is `null`, which isn't not super helpful.

I suggest:

```suggestion
      if (!(_err instanceof Error)) {
        throw new Error(`Error "${_err}" not instanceof Error`);
      } 
      
      err = _err;
```

2024-12-02 17:11 UTC, trek approved these changes

2024-12-02 17:20 UTC, TooTallNate requested changes

2024-12-02 17:20 UTC, TooTallNate commented on packages/client/package.json
> +    "vitest": "2.0.1",
Is this actually necessary? `vitest` is a dep in the root-level "package.json".

Also, looks like we're using a newer version at the root level `2.0.3`.

2024-12-02 17:21 UTC, merged