Pass `VERCEL_TELEMETRY_DISABLED` to flush command
vercel/vercel pull request #12583
Opened 2024-11-14 17:33 UTC by jeffsee55

Now calls `telemetry flush with `VERCEL_TELEMETRY_DISABLED=1` to avoid an infinite loop on `telemetryEventStore.save()`

[See comment](https://github.com/vercel/vercel/pull/12555#pullrequestreview-2434378618)

2024-11-14 17:33 UTC, trek submitted a review, later dismissed

2024-11-14 17:34 UTC, jeffsee55 commented on packages/cli/test/unit/util/telemetry-check-status.test.ts
> +      expect(client.getFullOutput()).toEqual('');
cc @trek I changed these tests to avoid using `.not.toOutput` (per Nate's [comment](https://github.com/vercel/vercel/pull/12555#pullrequestreview-2434385412))

2024-11-14 17:36 UTC, TooTallNate requested changes

2024-11-14 17:36 UTC, TooTallNate commented on packages/cli/src/util/telemetry/index.ts
> +import { cloneEnv } from '@vercel/build-utils/dist';
```suggestion
import { cloneEnv } from '@vercel/build-utils';
```

2024-11-14 21:57 UTC, erikareads commented
Have you tested this manually to verify that it works with the change?

2024-11-14 23:47 UTC, jeffsee55 commented
> Have you tested this manually to verify that it works with the change?

Yep 👍

2024-11-14 23:48 UTC, erikareads approved these changes

2024-11-15 18:08 UTC, TooTallNate approved these changes

2024-11-15 23:03 UTC, merged