[build-utils] Remove `VERCEL_ALLOW_NODEJS22` env var check
vercel/vercel pull request #12614
Opened 2024-11-19 19:24 UTC by TooTallNate

2024-11-19 21:10 UTC, EndangeredMassa approved these changes

2024-11-21 20:25 UTC, erikareads approved these changes

2024-11-21 20:29 UTC, onsclom approved these changes

2024-11-21 20:33 UTC, trek approved these changes

2024-11-22 03:40 UTC, EndangeredMassa requested changes
doing a dance to skip the merge queue

2024-11-22 03:40 UTC, merged