[cli] bump tsup and lint-staged
vercel/vercel pull request #12690
Opened 2024-12-03 22:12 UTC by erikareads

2024-12-09 21:09 UTC, trek approved these changes, later dismissed

2025-01-09 21:01 UTC, EndangeredMassa requested changes

2025-01-09 21:01 UTC, EndangeredMassa commented on packages/cli/scripts/compile-templates.mjs
> +import dot from 'dot';
<!-- Suggestion comments propose improvements to the code. Mention specifically what should be changed and what the benefit would be.  -->
**suggestion (blocking):** remove?

‏

2025-01-13 20:29 UTC, EndangeredMassa approved these changes

2025-01-13 20:52 UTC, trek approved these changes

2025-08-05 15:04 UTC, closed without merging