Add an option to copy symlinks
vercel/vercel pull request #191
Opened 2016-12-29 21:19 UTC by OlliV

2016-12-29 21:40 UTC, leo requested changes

2016-12-29 21:40 UTC, leo commented on bin/now-deploy.js
> +    -l, --links               Copy symlinks as symlinks
Let's make this a little more explicit:

> Don't resolve symlinks

2016-12-29 21:58 UTC, OlliV commented on bin/now-deploy.js
> +    -l, --links               Copy symlinks as symlinks
Should we also add an option to ignore permissions or file mode completely?

2016-12-29 22:18 UTC, rauchg commented on bin/now-deploy.js
> +    -l, --links               Copy symlinks as symlinks
Is it actually _not resolving symlinks_ ? I do agree that it needs re-wording, but not sure it's that one.

2016-12-29 22:19 UTC, rauchg commented
What's the spirit of this option?

2016-12-30 05:23 UTC, OlliV commented
@rauchg Currently it's not possible to use symlinks (with now-cli) in deployments because we always copy the contents of the file. So if you have a symlink to a file you just get two copies of the file inside the deployment instead of a symlink. With this option the user can opt-in for real symlinks.

2016-12-30 07:52 UTC, OlliV commented on bin/now-deploy.js
> +    -l, --links               Copy symlinks as symlinks
btw. that's the same wording as rsync is using 🙂

2016-12-30 17:44 UTC, merged