Refine test-unit task
vercel/vercel pull request #2028
Opened 2019-03-28 02:04 UTC by amio

- Include all `test/*unit.js`
- Include `.ts` extension
- Simplify report for meaningful review (removed `--all` arg)

![image](https://user-images.githubusercontent.com/215282/55124247-915c1a80-5140-11e9-9d0c-680020ac19c7.png)

2019-03-28 13:39 UTC, styfle approved these changes
This looks ok but let's get @leo to sign off on it too 👍

2019-03-28 21:38 UTC, leo requested changes
Please make the coverage reporting a separate Circle CI job and move over the needed files by attaching them to the workflow (see examples in the workflow list in the config file).

2019-03-29 08:20 UTC, amio commented
@leo just realize that there's no coverage output for integration tests 😅

Made coverage reporting a separate job, good to review now.

2019-03-29 10:46 UTC, leo approved these changes

2019-03-29 12:13 UTC, merged