Better builder logging
vercel/vercel pull request #2219
Opened 2019-04-24 08:55 UTC by amio

Reveal builder logs and prepend with `[builder-name]`.

![image](https://user-images.githubusercontent.com/215282/56646060-63231980-66b1-11e9-93ab-6f743c15055f.png)

2019-04-24 11:26 UTC, leo commented
@amio We don't want to reveal them all, we need to shorten them.

2019-04-24 11:26 UTC, leo requested changes
See comment

2019-04-25 01:28 UTC, amio commented on src/commands/dev/lib/dev-builder.ts
> +    if (log.startsWith(LOG_PREFIX_DEBUG)) {
Yea, I forgot that :P

2019-04-25 01:28 UTC, amio commented
We moved to another approach, closing this PR.

2019-04-25 01:28 UTC, closed without merging