Improve `now dev` output message
vercel/vercel pull request #2506
Opened 2019-07-08 13:25 UTC by sophearak

This PR improve output message better reflect zero-config.

2019-07-08 17:30 UTC, TooTallNate commented
Code seems ok to me, but how is this related to zero-config?

2019-07-09 04:01 UTC, sophearak commented
@TooTallNate So, we want user to completely forget about builders. since zero-config make it works out of the box, there are no need to mention builder in the output. 🙌

2019-07-09 10:13 UTC, leo requested changes

2019-07-09 10:13 UTC, leo commented on src/util/dev/builder.ts
> +        `Building... ${chalk.underline(entrypoint)}`
```suggestion
        `Preparing ${chalk.underline(entrypoint)} for build`
```

2019-07-09 10:14 UTC, leo approved these changes

2019-07-09 10:32 UTC, merged