Add more alias support
vercel/vercel pull request #2747
Opened 2019-08-12 14:03 UTC by nkzawa

2019-08-12 21:50 UTC, TooTallNate requested changes

2019-08-12 21:50 UTC, TooTallNate commented on src/util/domains/setup-domain.ts
> +import extactDomain from '../alias/extract-domain';
```suggestion
import extractDomain from '../alias/extract-domain';
```

2019-08-12 21:50 UTC, TooTallNate commented on src/util/domains/setup-domain.ts
> +  const aliasDomain = extactDomain(alias);
```suggestion
  const aliasDomain = extractDomain(alias);
```

2019-08-13 00:48 UTC, TooTallNate requested changes
The code looks good to me, but can we add an integration test for this?

2019-08-14 11:35 UTC, AndyBitz approved these changes

2019-08-16 00:24 UTC, TooTallNate commented on src/util/certs/get-wildcard-cns-for-alias.ts
> +export default function getWildcardCNSForAlias(alias: string) {
I like the camel casing like in the file above better.

```suggestion
export default function getWildcardCnsForAlias(alias: string) {
```

2019-08-16 00:27 UTC, TooTallNate approved these changes

2019-08-16 00:48 UTC, merged

2019-08-18 12:04 UTC, leo commented
Please remember to add a PR description @nkzawa.