Changed scale error message
vercel/vercel pull request #3394
Opened 2019-12-07 23:55 UTC by alepacheco

The error message does not give a clear reason of why it failed

2019-12-08 00:15 UTC, paulogdm commented
This command will be deleted soon @alepacheco , once Now 1.0 has a deprecation plan.

2019-12-16 14:08 UTC, styfle approved these changes
Thanks!

2019-12-16 17:49 UTC, AndyBitz requested changes
Left a comment with a suggestion.

Thank you for finding this 👍

2019-12-16 17:49 UTC, AndyBitz commented on packages/now-cli/src/commands/scale.js
> +    output.error('Cannot scale a V2 deployment');
```suggestion
    output.error('Cannot scale a Now 2.0 deployment');
```
We try to use `Now 2.0` when possible instead of `v2` for messages.

2019-12-16 21:14 UTC, AndyBitz approved these changes

2019-12-16 21:44 UTC, merged