feat: Read default dev port from .env
vercel/vercel pull request #3525
Opened 2020-01-08 23:25 UTC by pke

Adds support for specifying the default port via environment variable `PORT`.

`dotenv` is used to read that variable from `.env` files.
The default port remains 3000.

Helps to solve #2613

What tests are required, where do I hook them in at best?

2020-01-09 17:00 UTC, styfle requested changes
This will cause bugs for frameworks that launch their own dev server such as Gatsby.

Currently, `now dev` uses the `PORT` environment variable to proxy requests to the framework's dev server.

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-cli.md#develop

2020-01-09 20:52 UTC, pke commented
Thanks for your feedback.

> Currently, `now dev` uses the `PORT` environment variable to proxy requests to the framework's dev server.

I am not sure I understand what the implications are here. The code I changed is run when framework dev servers are run or not? Why does it matter, when `now` not mounts the port itself, reading the env var does no harm, does it?

2020-01-09 21:17 UTC, TooTallNate reviewed
The code LGTM, but would it be possible to add a new test case for this behavior?

2020-01-09 21:18 UTC, styfle reviewed
On second thought, the PORT is assigned to the child process so this PR wouldn't be an issue

https://github.com/zeit/now/blob/master/packages/now-static-build/src/index.ts#L351

Disregard my previous comment.

2020-01-10 00:04 UTC, pke commented
Do you have any idea where such test could live? Do we already have tests that involve the `.env` file?

2020-01-13 22:38 UTC, TooTallNate commented
I don't think it needs to read the `.env` file specifically, but test that spawning the process with the `PORT` env var defined would be enough in my opinion.

2020-01-14 07:57 UTC, pke commented
> I don't think it needs to read the `.env` file specifically, but test that spawning the process with the `PORT` env var defined would be enough in my opinion.

What if it does not spawn a process but provides the server itself? None of the mentioned scenarios collides with the marginal change this PR provides.
I like to see `now dev` working with standard node apps first and with other frameworks as an addon (that's why it requires an entry in the `now.json` file to work with other frameworks).

2022-11-08 21:34 UTC, andymckay commented
Based on the fact that this has been open for over 2 years, I'm going to close it in an effort to clean up the backlog. If you want to keep working on it, my apologies and please re-open it.

2022-11-08 21:34 UTC, closed without merging

2022-11-09 04:30 UTC, jerrygreen reviewed
Yes but why this wasn’t been merged in the first place? Because it didn’t had a test?

It’s a good feature: having to be able to read CLI parameters from env as an option is a good feature overall (well unless they don’t override cli parameters, in which case they don’t).

`PORT` is one of the most important one, though I personally wouldn’t mind having env var equivalents for all cli parameters, so they can be stored in a file rather than passed to cli each time.

I only not sure why dotenv wasn’t been moved to package’s main dependencies. Won’t this raise an error?

2022-11-09 04:30 UTC, jerrygreen commented on packages/now-cli/src/commands/dev/dev.ts
> +import 'dotenv/config';
Shouldn’t this line break users projects that aren’t having `dotenv`? I mean, this package isn’t listed in dependencies for the cli, it only listed as `devDependency`. If we fix that, I would say LGTM.