update ionic-react placeholders
vercel/vercel pull request #3925
Opened 2020-03-17 16:42 UTC by mhartington

👋 hello there.

This updates the Ionic React placeholders to better match a real app.

2020-03-21 19:20 UTC, leo requested changes
Thank you for your contribution! The Output Directory change looks great, but I'd be great if the Dev Command would be the framework's dev command itself, so that no other program is run in between.

2020-03-23 13:56 UTC, mhartington commented
@leo the idea here is that if user eject from react-scripts, then calling `react-scripts start` would cause an error. If things default to `npm run start`, that at least covers both ejected and non-ejected setups.

2020-03-30 19:58 UTC, styfle submitted a review, later dismissed

2020-06-02 14:43 UTC, styfle commented
Thanks for this PR!

It looks like this has already been fixed on `master` so I'm going to close.

2020-06-02 14:43 UTC, closed without merging