[cli] Fix `vc env pull` escaping quotes
vercel/vercel pull request #4412
Opened 2020-05-18 22:51 UTC by styfle

Fixes an issue from discussion #4391

2020-05-18 22:52 UTC, lucleray submitted a review, later dismissed

2020-05-18 23:35 UTC, TooTallNate requested changes
Test is still failing

2020-05-19 00:02 UTC, TooTallNate approved these changes

2020-05-19 12:35 UTC, lucleray approved these changes

2020-05-19 12:37 UTC, merged