[node][next] Bump node-file-trace to 0.6.4
vercel/vercel pull request #4617
Opened 2020-06-10 13:49 UTC by styfle

Bump node-file-trace to fix a webpack tracing bug that looks like the following:

```
TypeError: Cannot read property 'type' of null
    at handleWrappers (/vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:12763:58)
    at module.exports.447.module.exports (/vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:14674:3)
    at Job.emitDependency (/vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:11730:40)
    at /vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:11755:20
    at async Promise.all (index 9)
    at async Job.emitDependency (/vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:11736:5)
    at async Promise.all (index 1)
    at async Object.module.exports.328.module.exports [as default] (/vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:11514:3)
    at async Object.module.exports.178.exports.build (/vercel/e77875438c1cd74b/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:6076:69)
    at async buildStep (/var/task/sandbox-worker.js:20407:20)
```

- [0.6.2](https://github.com/vercel/node-file-trace/releases/tag/0.6.2)
- [0.6.3](https://github.com/vercel/node-file-trace/releases/tag/0.6.3) 
- [0.6.4](https://github.com/vercel/node-file-trace/releases/tag/0.6.4)

Depends on #4355

2020-06-10 13:49 UTC, Timer submitted a review, later dismissed

2020-06-10 14:02 UTC, ijjk requested changes
Looks like we need to add handling for the `@vercel/next` integration tests that are failing:

```
● Should build the standard example

    TypeError: Cannot read property 'declarations' of undefined

      12854 |                   }
      12855 |                   else if (parent.arguments && parent.arguments.some(arg => arg === node)) {
    > 12856 |                     delete parent.scope.declarations[node.id];
            |                                         ^
      12857 |                     parent.arguments = parent.arguments.map(arg => arg === node ? replacement : arg);
      12858 |                   }
      12859 |                   else if (parent.init === node) {
```

2020-06-15 17:52 UTC, ijjk approved these changes

2020-06-15 20:19 UTC, Timer approved these changes

2020-06-15 20:21 UTC, TooTallNate approved these changes

2020-06-15 20:45 UTC, merged