[@vercel/build-utils] Improve Nuxt build
vercel/vercel pull request #4755
Opened 2020-07-01 15:06 UTC by Atinux

Need review from @pi0 and @danielroe

2020-07-02 19:53 UTC, TooTallNate submitted a review, later dismissed

2020-07-02 20:35 UTC, danielroe commented on packages/now-static-build/src/frameworks.ts
> +      },
```suggestion
      },
      {
        src: '/_nuxt/(.*)',
        headers: { 'cache-control': 'public,max-age=31536000,immutable' },
        continue: true,
      },
```

2020-07-02 20:37 UTC, danielroe requested changes

2020-07-02 20:37 UTC, danielroe commented on packages/now-static-build/src/frameworks.ts
> +      },
```suggestion
      },
      {
        src: '/_nuxt/(.*)',
        headers: { 'cache-control': 'public,max-age=31536000,immutable' },
        continue: true,
      },
```

2020-07-10 15:59 UTC, styfle approved these changes
Thanks!

2020-07-10 16:02 UTC, AndyBitz approved these changes

2020-07-10 16:41 UTC, merged