Add Important Headers to Next.js to Avoid Users Overriding Cache Headers
vercel/vercel pull request #5452
Opened 2020-11-20 14:35 UTC by dav-is

### Related Issues

https://app.clubhouse.io/vercel/story/14921/add-important-headers-to-routes

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [ ] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

2020-11-20 15:51 UTC, styfle approved these changes, later dismissed

2020-11-20 21:17 UTC, ijjk submitted a review, later dismissed
LGTM, revalidate tests should pass after test wait times are bumped in https://github.com/vercel/vercel/pull/5454

2020-11-24 22:17 UTC, newblaque submitted a review, later dismissed

2020-11-26 00:14 UTC, Timer requested changes, later dismissed
We need to add a test case for this

2020-12-01 21:03 UTC, ijjk approved these changes

2020-12-01 21:04 UTC, styfle approved these changes

2020-12-01 22:08 UTC, merged