Use proper Apache format
vercel/vercel pull request #6189
Opened 2021-05-06 02:19 UTC by matheuss

The existing LICENSE file was missing the Appendix, and also using weird formatting. This PR makes it be an exact copy of the original https://www.apache.org/licenses/LICENSE-2.0.txt.

2021-05-06 02:21 UTC, joecohens approved these changes

2021-05-06 02:48 UTC, TooTallNate requested changes

2021-05-06 02:48 UTC, TooTallNate commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
```suggestion
   Copyright 2017 Vercel, Inc.
```

2021-05-07 20:49 UTC, styfle reviewed
Also needs to be updated here https://github.com/vercel/vercel/blob/038c228af412eb2aa9c3ec2eb05f0fac40fe89df/package.json#L5

2021-05-25 20:26 UTC, TooTallNate approved these changes

2021-05-25 20:27 UTC, merged