Ask for value of missing environment variables
vercel/vercel pull request #645
Opened 2017-06-07 14:12 UTC by leo

If your `env` config property contains an array instead of an object, `now` will ask you for the value of these environment variables. This makes the initial command much shorter (no `-e` needed)!

**BEFORE**

```bash
now -e SLACK_API_TOKEN="<token>" \
     -e SLACK_SUBDOMAIN="<team-name>" \
     -e GOOGLE_CAPTCHA_SECRET="<secret>" \
     -e GOOGLE_CAPTCHA_SITEKEY="<sitekey>" \
     now-examples/slackin
```

**AFTER**

```bash
now now-examples/slackin
```

```json
"env": [
  "SLACK_API_TOKEN",
  "SLACK_SUBDOMAIN",
  "GOOGLE_CAPTCHA_SECRET",
  "GOOGLE_CAPTCHA_SITEKEY"
]
```

[This](https://github.com/rauchg/slackin/pull/312) is how we do it.

2017-06-08 18:32 UTC, matheuss requested changes

2017-06-08 18:32 UTC, matheuss commented on bin/now-deploy.js
> +    '> Please enter the values for the following environment variables:'
Please use the `info` helper 🙏

2017-06-08 18:32 UTC, matheuss commented on bin/now-deploy.js
> +  console.log(nowConfig.env)
This shouldn't be here right 😅

2017-06-08 18:32 UTC, matheuss commented on bin/now-deploy.js
> +  if (Array.isArray(nowConfig.env)) {
This breaks deployments that don't have a `now` on `package.json` or a `now.json`:
![image](https://user-images.githubusercontent.com/4721750/26944564-f0a6c288-4c3d-11e7-9435-9bfa7e727951.png)

2017-06-09 14:54 UTC, leo commented
Thank you, @matheuss. Applied your wishes! 😊

2017-06-09 19:22 UTC, matheuss approved these changes
✅

2017-06-09 19:24 UTC, matheuss requested changes
👎 
![image](https://user-images.githubusercontent.com/4721750/26991280-9d82d12e-4d0e-11e7-95a9-9603b70bb75f.png)

2017-06-10 13:41 UTC, leo commented
@matheuss Done!

2017-06-12 14:24 UTC, merged