Make clipboard copying in `vc deploy` opt-in
vercel/vercel pull request #8085
Opened 2022-07-05 21:31 UTC by MatthewStanciu

https://vercel.slack.com/archives/C03F2CMNGKG/p1656971502881949

Right now, `vc deploy` automatically copies the deploy url to your clipboard after the deployment has finished. You can opt out via the `--no-clipboard` flag, but it's enabled by default.

This is strange behavior—there's no indication that the CLI will hijack your clipboard, and you don't know until after it happens.

This PR replaces the `--no-clipboard` flag with a `--clipboard` flag, making the clipboard copying feature opt-in instead of opt-out.

### 📋 Checklist

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [ ] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

2022-07-05 22:31 UTC, styfle approved these changes
Seems good. I would take it a step further and remove the feature completely. Instead, rely on the terminal printing the necessary information and the user clicking to open the url.

2022-07-05 22:38 UTC, MatthewStanciu commented
I'm on board with that!

2022-07-05 22:49 UTC, styfle commented on packages/cli/src/commands/deploy/args.ts
> +    -C, --clipboard                Copy URL to clipboard after deployment
This should be removed

Also the docs need to be removed here https://vercel.com/docs/cli#introduction/unique-options/no-clipboard

2022-07-05 22:51 UTC, styfle requested changes
The help message needs to be updated.

Also the docs need to be removed here https://vercel.com/docs/cli#introduction/unique-options/no-clipboard

2022-07-05 22:59 UTC, styfle approved these changes

2022-07-06 16:42 UTC, EndangeredMassa approved these changes

2022-07-06 16:56 UTC, TooTallNate commented on test/benchmark.js
>  const { mkdirSync, writeFileSync } = require('fs');
I'm not even sure what this file is. Perhaps we should delete it if it's not being used by CI.

2022-07-06 17:07 UTC, TooTallNate approved these changes

2022-07-06 18:04 UTC, merged