[tests] Add yarn cache to github actions
vercel/vercel pull request #8567
Opened 2022-09-14 21:54 UTC by styfle

We had this enable for some workflows but not all so this PR enables the yarn cache for the remaining workflows.

2022-09-14 22:21 UTC, cb1kenobi approved these changes
LGTM

2022-09-14 22:27 UTC, TooTallNate requested changes
Looks like we need to run checkout before setup-node

2022-09-15 01:32 UTC, ijjk approved these changes

2022-09-15 01:44 UTC, TooTallNate approved these changes

2022-09-15 02:05 UTC, merged