[cli] Allow `vc link` to overwrite existing link
vercel/vercel pull request #8845
Opened 2022-11-03 20:14 UTC by TooTallNate

There was a regression in #8670 which caused `vc link` to be a no-op when there was already a link to a Vercel project in the `.vercel` directory.

2022-11-03 20:15 UTC, styfle approved these changes
Thanks! How about adding a test?

2022-11-03 20:19 UTC, cb1kenobi requested changes

2022-11-03 20:19 UTC, cb1kenobi commented on packages/cli/src/util/link/ensure-link.ts
> +  if (opts.forceDelete || link.status === 'not_linked') {
It's possible that `link.status` will equal `"error"`, so you need to explicitly check the link status is `"linked"` in addition to `opts.forceDelete`:

```suggestion
  if ((link.status === 'linked' && opts.forceDelete) || link.status === 'not_linked') {
```

2022-11-04 18:57 UTC, cb1kenobi approved these changes
Looks good!

2022-11-04 19:12 UTC, merged