Updated Nuxt starter to v3
vercel/vercel pull request #8928
Opened 2022-11-16 23:13 UTC by steven-tey

### Related Issues

> Fixes #1
> Related to #2

### 📋 Checklist

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [ ] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

2022-11-16 23:27 UTC, leerob commented on examples/nuxtjs/README.md
> +# Nuxt 3 Minimal Starter
```suggestion
# Nuxt Example

Deploy your [Nuxt](https://nuxt.com) project to Vercel with zero configuration.

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/vercel/vercel/tree/main/examples/nuxtjs&template=nuxtjs)

_Live Example: https://nuxtjs-template.vercel.app_
```

2022-11-16 23:28 UTC, leerob commented on examples/nuxtjs/README.md
> +Look at the [nuxt 3 documentation](https://v3.nuxtjs.org) to learn more.
```suggestion
Look at the [Nuxt 3 documentation](https://v3.nuxtjs.org) to learn more.
```

2022-11-16 23:28 UTC, leerob commented on examples/nuxtjs/package.json
> +    "nuxt": "3.0.0"
```suggestion
    "nuxt": "^3.0.0"
```

2022-11-16 23:28 UTC, leerob requested changes
Can we use pnpm please?

2022-11-17 20:04 UTC, steven-tey commented
@leerob done!

2022-11-17 20:26 UTC, leerob approved these changes

2022-11-17 20:27 UTC, merged