[next] Use MIB for Lambda constants
vercel/vercel pull request #8991
Opened 2022-11-30 16:50 UTC by Kikobeats

According to AWS Lambda official documentation:

> The Lambda documentation, log messages, and console use the abbreviation MB (rather than MiB) to refer to 1024 KB.

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

This is also a convenient thing for us since CF Limits are in base-2 (even they are printed as base-10).

2022-11-30 17:16 UTC, styfle reviewed
Looks like CI is failing because the error message says

> Max serverless function size of 47.68 MB compressed or 250 MB uncompressed

2022-11-30 17:24 UTC, cb1kenobi commented
Should these https://github.com/vercel/vercel/blob/7fbb3d7e993d24cde55bc26f4b4f9a01643529c2/packages/next/src/utils.ts#L1545-L1547 also use `MIB`?

2022-12-01 02:43 UTC, ijjk commented on packages/next/src/utils.ts
> +      if (dep.compressed < 100 * MIB && dep.uncompressed < 500 * MIB) {
```suggestion
      if (dep.compressed < 100 * KIB && dep.uncompressed < 500 * KIB) {
```

2022-12-01 08:32 UTC, Kikobeats commented on packages/next/src/utils.ts
> +      if (dep.compressed < 100 * MIB && dep.uncompressed < 500 * MIB) {
ouch, good catch

2022-12-07 14:42 UTC, cb1kenobi requested changes

2022-12-07 14:42 UTC, cb1kenobi commented on packages/next/src/utils.ts
> +const LAMBDA_RESERVED_COMPRESSED_SIZE = 250 * MIB;
```suggestion
const LAMBDA_RESERVED_COMPRESSED_SIZE = 250 * KIB;
```

2022-12-07 16:44 UTC, Kikobeats commented on packages/next/src/utils.ts
> +const LAMBDA_RESERVED_COMPRESSED_SIZE = 250 * MIB;
oh, thanks!

2022-12-07 20:23 UTC, cb1kenobi approved these changes
LGTM!

2022-12-10 07:33 UTC, TooTallNate approved these changes

2022-12-13 05:27 UTC, merged