[tests] Disable Turbo's update notifier
vercel/vercel pull request #9302
Opened 2023-01-24 18:04 UTC by cb1kenobi

Since switching to the canary releases of Turbo, we are seeing the update notification often. We have a cron job (https://github.com/vercel/vercel/pull/9301) that will keep this up-to-date for us, so we don't need to have Turbo notify us of updates.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/97262/214372374-a2682014-2deb-4942-b694-fd140c26a6ef.png">

2023-01-24 18:10 UTC, Ethan-Arrowood approved these changes, later dismissed
is there some kind of global config for turbo so we don't have to pass it in every command?

2023-01-24 18:12 UTC, cb1kenobi commented
> is there some kind of global config for turbo so we don't have to pass it in every command?

Not that I'm aware of. Based on the code, it appears the environment variable is the only option: https://github.com/vercel/turbo/blob/5232e179a408f24da2ecc7da6d6d42c6985a9a67/crates/turbo-updater/src/lib.rs#L80-L88.

2023-01-24 21:29 UTC, styfle reviewed
This doesn't work on windows https://github.com/vercel/vercel/actions/runs/3999082420/jobs/6862537077#step:8:15

2023-01-24 21:32 UTC, cb1kenobi commented
@styfle could we ask the turbo team to add a flag to disable the update notifier?

2023-01-24 21:32 UTC, EndangeredMassa requested changes

2023-01-24 21:32 UTC, EndangeredMassa commented on package.json
> +    "test-integration-dev": "node utils/gen.js && NO_UPDATE_NOTIFIER=1 turbo run test-integration-dev",
This will fail on windows, won't it? Maybe we should use [cross-env](https://github.com/kentcdodds/cross-env#readme) or some other solution.

2023-02-28 21:15 UTC, cb1kenobi commented
`turbo` now has support for a `--no-update-notifier` flag! https://github.com/vercel/turbo/pull/4003

Thanks @tknickman!

2023-02-28 21:16 UTC, styfle approved these changes, later dismissed

2023-02-28 21:36 UTC, cb1kenobi commented
Yikes, I think we should wait for the `turbo` dependency to be updated first.

2023-03-22 19:31 UTC, EndangeredMassa approved these changes

2023-03-22 19:39 UTC, merged