[fs-detectors] getMonorepoDefaultSettings: Fix settings
vercel/vercel pull request #9315
Opened 2023-01-25 20:39 UTC by chloetedder

1. `commandForIgnoringBuildStep` should be run at the project directory level not the monorepo root level
2. Simplifying the `installCommand` because doesn't need the relative root unless it is `npm`

2023-01-25 20:52 UTC, Ethan-Arrowood approved these changes, later dismissed

2023-01-25 21:45 UTC, Ethan-Arrowood commented
https://github.com/vercel/vercel/actions/runs/4009863452/jobs/6885709398#step:10:1776 looks like there are some unit tests to fix

2023-01-25 23:27 UTC, styfle commented on packages/fs-detectors/test/fixtures/get-monorepo-default-settings/turbo-npm/packages/app-1/package.json
> +  "name": "app-1",
Lets use a more specific name so it doesn't collide

2023-01-25 23:28 UTC, styfle requested changes
We have tons of warnings due to the repeated names

- https://github.com/vercel/vercel/pull/9317

Lets either use a unique `name`, or if its not needed use `private: true`

2023-01-26 16:42 UTC, styfle approved these changes, later dismissed

2023-01-30 18:29 UTC, Ethan-Arrowood approved these changes

2023-01-30 18:35 UTC, merged