[remix-entry-server] Add initial implementation
vercel/vercel pull request #9417
Opened 2023-02-10 22:07 UTC by TooTallNate

2023-02-13 19:48 UTC, Ethan-Arrowood submitted a review, later dismissed

2023-02-13 22:45 UTC, EndangeredMassa approved these changes, later dismissed

2023-02-13 22:45 UTC, EndangeredMassa commented on packages/remix-entry-server/README.md
> +
**suggestion (non-blocking):** be more explicit

Can we write something here to be more explicit about how to use this? Maybe something like:

```suggestion

Make sure `@vercel/remix-entry-server` is installed with your favorite package manager, then replace your `app/entry.server.tsx` file with the following:

```

2023-02-14 04:50 UTC, cb1kenobi requested changes
`serveTheBots()` and `serveBrowsers()` are so similar. It seems `onAllReady()` and `onShellReady()` are identical aside from `didError` which seems harmless for the bot path. I dunno how much more time you want to put into this, but there seems like room for some cute code reuse.

2023-02-14 04:50 UTC, cb1kenobi commented on packages/remix-entry-server/package.json
> +    "@types/react-dom": "18.0.10",
For safety, it's probably a good idea to add `execa` and `fs-extra` to the `devDependencies`.

2023-02-14 08:14 UTC, TooTallNate commented
@cb1kenobi The code is actually direct copy+paste from the Remix Streaming docs page, I wanted to keep it "official".

2023-02-14 17:11 UTC, cb1kenobi approved these changes

2023-02-14 17:34 UTC, EndangeredMassa approved these changes

2023-02-14 17:59 UTC, Ethan-Arrowood approved these changes

2023-02-14 18:09 UTC, merged