As of turbo@1.8 all filters are inferred.
vercel/vercel pull request #9680
Opened 2023-03-16 02:59 UTC by nathanhammond

We no longer need to specify the active folder for `turbo` to identify the context correctly.

2023-03-16 12:58 UTC, tknickman requested changes, later dismissed
This is not true until we have global turbo available.

2023-03-17 17:03 UTC, Ethan-Arrowood submitted a review, later dismissed
looking good!

2023-03-17 17:03 UTC, Ethan-Arrowood commented on packages/fs-detectors/src/monorepos/get-monorepo-default-settings.ts
> +      if (turboSemVer && !semver.intersects(turboSemVer, '<1.8.0')) {
i've found `semver.satisfies` to be a bit clearer 

```suggestion
      if (turboSemVer && semver.satisfies(turboSemVer, '<1.8.0')) {
```

2023-03-17 17:03 UTC, Ethan-Arrowood commented on packages/fs-detectors/test/fixtures/get-monorepo-default-settings/turbo-new/package.json
lets call this turbo-1.8 instead of turbo-new. I assume in the future there will be a _newer_ turbo and we'll want to keep this test around

2023-03-18 00:40 UTC, nathanhammond commented on packages/fs-detectors/src/monorepos/get-monorepo-default-settings.ts
> +      if (turboSemVer && !semver.intersects(turboSemVer, '<1.8.0')) {
We can't switch to satisfies. We need to check to see if the version could *possibly* match anything less than 1.8.0 since we're not querying the lockfile. This is intentionally an intersection check.

2023-03-18 00:41 UTC, nathanhammond commented on packages/fs-detectors/test/fixtures/get-monorepo-default-settings/turbo-new/package.json
I'll switch to turbo-has-filter; the 1.8.0 boundary won't change for that and it's more clear, meeting your goal. 👍

2023-03-31 20:04 UTC, Ethan-Arrowood approved these changes

2023-03-31 21:02 UTC, merged