draft
vercel/vercel pull request #9688
Opened 2023-03-17 20:11 UTC by EndangeredMassa

2023-03-21 14:41 UTC, styfle commented on packages/cli/package.json
> +    "test-cli": "rimraf test/fixtures/integration && pnpm test test/integration-1.test.ts test/integration-2.test.ts test/integration-3.test.ts",
I think `test-cli` could be renamed to `test-e2e` since it is creating deployments in many cases and then you wouldn't need to touch `chunk-tests.js`

2023-03-27 15:30 UTC, EndangeredMassa commented on packages/cli/package.json
> -    "test-cli": "rimraf test/fixtures/integration && pnpm test test/integration.test.ts",
We should probably move these to `test/integration/*`

2023-03-27 17:47 UTC, TooTallNate approved these changes, later dismissed

2023-03-28 18:54 UTC, cb1kenobi requested changes

2023-03-28 18:54 UTC, cb1kenobi commented on packages/cli/test/unit/commands/rollback.test.ts
> +  xw;
Extra characters?

2023-03-28 22:37 UTC, EndangeredMassa commented on packages/cli/test/unit/commands/rollback.test.ts
> +  xw;
Ack. Fixed: [`1efd3ca` (#9688)](https://github.com/vercel/vercel/pull/9688/commits/1efd3ca961f0b6df01cde38e6a3b1b80196b5dad)

2023-03-29 05:37 UTC, cb1kenobi approved these changes
Looks good!

2023-03-29 07:44 UTC, merged