[go] Support 'go.work' file and resolve shared deps relative to work path
vercel/vercel pull request #9708
Opened 2023-03-23 19:35 UTC by cb1kenobi

This PR fixes a few issues related to `vc dev`.

1. Create a default `go.work` file in the cache dir when building the `vercel-dev-server-go` executable.
2. Copy the existing `go.mod` file into the cache dir and update any "replace" relative paths.

Linear: https://linear.app/vercel/issue/VCCLI-638/vc-dev-go-builder-cant-resolve-workspace-dependencies

2023-03-23 21:09 UTC, styfle commented on packages/go/test/fixtures/26-go-work-with-shared/vercel.json
> +}
This vercel.json file can be removed

2023-03-23 21:09 UTC, styfle reviewed
> This PR fixes a few issues related to `vc dev`

Can you add a vc dev test?

For example: https://github.com/vercel/vercel/blob/ad107ecf79a15082dff683855e066d0b251e9127/packages/cli/test/dev/integration-2.test.ts#L172-L183

2023-03-24 01:05 UTC, vedantmgoyal2009 commented
Please give the URL for this PR which I can put in `VERCEL_CLI_VERSION` environment variable and test it.

2023-03-29 22:03 UTC, cb1kenobi commented on packages/go/test/fixtures/26-go-work-with-shared/vercel.json
> +}
Done!

2023-03-30 18:21 UTC, vedantmgoyal2009 approved these changes, later dismissed
Fixes #9393. Thanks a lot for #9576 and this :shipit:

2023-03-30 20:31 UTC, EndangeredMassa requested changes
This go project works with latest `vercel`, but not with this branch: https://github.com/EndangeredMassa/rdhawladar-golang-vercel

> api/entrypoint.go:8:2: package golang-vercel/docs is not in GOROOT (/Users/smassa/source/demo/golang-vercel/.vercel/cache/golang/src/golang-vercel/docs)
> Error: Command failed: go build -ldflags -s -w -o ./vercel-dev-server-go ./...

2023-04-13 17:48 UTC, EndangeredMassa approved these changes
I tested some Go projects with this and everything seems to work. Thanks!

2023-04-13 17:59 UTC, merged

2023-05-24 12:37 UTC, vedantmgoyal2009 commented
@cb1kenobi #10016. Also, I tried prefixing files with "_" (underscore) as mentioned in https://vercel.com/docs/concepts/functions/serverless-functions#adding-utility-files-to-the-/api-directory, but it seems that it also gets ignored.

2023-05-24 14:31 UTC, cb1kenobi commented
@vedantmgoyal2009 Yeah, I don't think the underscore convention works with Go serverless functions. Go support is still considered beta. I think we would need to do a bit of refactoring to support this and it would be a good thing to do. :)

2023-05-24 16:01 UTC, vedantmgoyal2009 commented
Since we don't have to do any debugging this time, I don't think it should take much longer. Actually, my project is still in development and I'm trying to implement the best ways to do a thing that leads to these types of feature requests. Hope I helped in polishing up your lib...

2023-06-01 14:21 UTC, cb1kenobi commented
@vedantmgoyal2009 sorry, I haven't had time to look into it. I created an issue in our internal ticket system, but we haven't prioritized it yet. Go support it beta and so there will be functionality gaps like the underscore prefix.